# Generated by Django 4.0.3 on 2022-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make_text', models.CharField(max_length=200)),
                ('car_model_text', models.CharField(max_length=200)),
                ('car_year_number', models.IntegerField(max_length=4)),
                ('car_bpm_number', models.IntegerField(max_length=3)),
                ('car_last_updated_date', models.DateTimeField()),
            ],
        ),
    ]
