# Generated by Django 4.0.3 on 2022-03-07 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbpm',
            name='car_bpm_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='carbpm',
            name='car_year_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
