# Generated by Django 4.0.3 on 2022-03-07 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_alter_carbpm_car_bpm_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbpm',
            name='car_bpm_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Car BPM'),
        ),
        migrations.AlterField(
            model_name='carbpm',
            name='car_last_updated_date',
            field=models.DateTimeField(verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='carbpm',
            name='car_make_text',
            field=models.CharField(max_length=200, verbose_name='Car Make'),
        ),
        migrations.AlterField(
            model_name='carbpm',
            name='car_model_text',
            field=models.CharField(max_length=200, verbose_name='Car Model'),
        ),
        migrations.AlterField(
            model_name='carbpm',
            name='car_year_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Car Year'),
        ),
    ]
